### ISSUE TITLE
能否提供一下数据下载链接？

### ISSUE THREAD

**Issue by YuqiChen4188** [DianboWork/SPN4RE#1]
如题

**Comment by DianboWork** [comment]
data文件夹已经更新，我的数据都是已经处理好的，可以使用。原始数据可以在https://github.com/xiangrongzeng/multi_re 和 https://github.com/weizhepei/casrel 下载

**Comment by YuqiChen4188** [comment]
models.setpred4re中   SetPred4RE模型似乎忘记定义criterion  导致第28行报错

**Comment by DianboWork** [comment]
已经更新了model.setpred4re
