### ISSUE TITLE
代码超参数错误

### ISSUE THREAD

**Issue by zyccyz** [DianboWork/SPN4RE#11]
您好，看了您的论文，很喜欢您的工作。不过命令行里似乎写成了num_generated_triplets，而main函数似乎少了个t导致该参数始终是10。
![image](https://user-images.githubusercontent.com/44648619/116658376-6f3dc200-a9c2-11eb-8e83-bfdfb45a2e6b.png)

**Comment by DianboWork** [comment]
非常感谢！！！

**Comment by DianboWork** [comment]
我已经修改了readme
