### ISSUE TITLE
我换成中文数据集，出现这个错误，请问是啥情况，是bert的原因吗

### ISSUE THREAD

**Issue by ysgncss** [DianboWork/SPN4RE#13]
IndexError: index out of range in self

**Comment by DianboWork** [comment]
建议把错误报全

**Comment by ysgncss** [comment]
=== Epoch 0 train ===
Traceback (most recent call last):
  File "C:/Users/kdecm/Desktop/临时文件/SPN4RE-main/main.py", line 100, in <module>
    trainer.train_model()
  File "C:\Users\kdecm\Desktop\临时文件\SPN4RE-main\trainer\trainer.py", line 77, in train_model
    loss, _ = self.model(input_ids, attention_mask, targets)
  File "D:\anaconda3\envs\python37\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\kdecm\Desktop\临时文件\SPN4RE-main\models\setpred4RE.py", line 22, in forward
    last_hidden_state, pooler_output = self.encoder(input_ids, attention_mask)
  File "D:\anaconda3\envs\python37\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\kdecm\Desktop\临时文件\SPN4RE-main\models\seq_encoder.py", line 17, in forward
    last_hidden_state, pooler_output = self.bert(input_ids, attention_mask=attention_mask)
  File "D:\anaconda3\envs\python37\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\anaconda3\envs\python37\lib\site-packages\transformers\modeling_bert.py", line 783, in forward
    input_ids=input_ids, position_ids=position_ids, token_type_ids=token_type_ids, inputs_embeds=inputs_embeds
  File "D:\anaconda3\envs\python37\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\anaconda3\envs\python37\lib\site-packages\transformers\modeling_bert.py", line 174, in forward
    position_embeddings = self.position_embeddings(position_ids)
  File "D:\anaconda3\envs\python37\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\anaconda3\envs\python37\lib\site-packages\torch\nn\modules\sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "D:\anaconda3\envs\python37\lib\site-packages\torch\nn\functional.py", line 1724, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self

**Comment by DianboWork** [comment]
torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse) 这里出错了，检查一下input_ids

**Comment by ysgncss** [comment]
tensor([[ 101, 9960, 3621,  123,  119,  100, 5905, 1921, 6817, 1220, 4276,  142,
         2940, 6121, 5016,  142, 3297, 4007, 2692, 4638, 2218, 3221, 2124, 4638,
         1912, 6225,  749, 8024, 3680, 3613, 2458, 4708, 2124, 1139, 6121, 4638,
         1726, 1928, 4372, 6963, 3221, 2523, 7770, 4638,  511, 3297,  679, 4007,
         2692, 4638, 2218, 3221, 2697, 6230, 3175, 1403, 4669, 1762, 2802, 6629,
         6760, 1403, 3341, 3300, 6929,  720, 4157, 1036, 3756, 7028, 2697, 8024,
         2769, 6230, 2533, 6821, 4157, 6820, 3221, 7444, 6206, 1400, 3309, 3300,
         2521, 1217, 2487, 4638,  511, 1296, 4692, 6821, 1378, 6756, 4638, 6756,
         6716, 2218, 6639,  809, 6432, 3209, 2124, 4638, 1079, 6956, 4958, 7313,
         6820, 3221, 3683, 6772, 2160, 3139, 4638, 8024, 3684, 4994, 6756, 6766,
         6655, 6963, 2923, 1920, 4638, 8024, 5445,  684, 2357, 2229,  738, 3221,
         3683, 6772, 1394, 4415, 4638, 8024,  679, 5052, 1777, 1762, 6756, 4638,
          818,  862,  855, 5390, 8024, 6963, 3221,  679,  833, 6230, 2533, 2881,
         2915, 1469, 2728, 2235, 4638,  511, 1220, 1213,  738, 3221, 2523, 5314,
         1213, 4638, 8024, 6629, 3635, 6813, 6862,  679, 5489, 8024, 4255, 1355,
         1213, 6820, 3221, 2523, 2487, 1226, 4638, 8024, 1400, 3309, 2990, 6862,
          738, 3221, 2523, 6813, 6862, 4638, 8024, 1762, 7770, 6862,  677, 1146,
         1146, 7164, 2218, 5543, 2130, 2768, 6631, 6756, 8024, 2697, 6230, 6820,
         3221, 2523, 4267,  812, 1036, 4638,  511, 3082, 2971, 6629, 3341,  738,
         3221, 3683, 6772, 2159, 3211,  677, 2797, 4638, 8024, 1825, 3315,  677,
          794, 2990, 6756, 1726, 3341, 3766, 6814, 1914,  719, 2218, 5543, 2523,
         4225, 5298, 4638, 2958, 2995,  857, 2124,  749, 8024,  852, 3221, 2697,
         6230, 3175, 1403, 4669, 1762, 2802, 6760, 1403, 4638, 3198,  952, 3300,
         6929,  720, 4157, 1036, 3756, 7028, 2697,  511, 3779, 5450,  738, 3221,
         2523, 5307, 3845, 4638, 8024, 1086, 1217,  677, 2769, 6624, 7770, 6862,
         4638, 3198,  952,  738, 3683, 6772, 1914, 8024, 2792,  809, 3683, 2769,
         4638, 7564, 3309,  738, 3221, 6820, 6206,  856, 4638, 8024, 5050,  678,
         3341,  679, 6814,  738, 2218,  673,  702, 4157, 1036, 1914, 4638, 3416,
         2094, 1416,  511, 2429, 3488, 4638, 6763, 4801, 3683, 6772, 6844,  704,
         8024, 1259, 6181, 2595, 6820, 3221, 2523, 2487, 4638, 8024, 5520, 7479,
         2190, 5587, 6956,  738, 5543, 6629, 1168,  671,  702, 2523, 2487, 4638,
         3118, 3053, 2595,  868, 4500, 8024, 3680, 3613, 2458, 4708, 2124, 6963,
          679,  833, 6230, 2533, 5587, 7000, 5520, 4563,  511, 1912, 6225, 3221,
         2247,  754, 6817, 1220, 3836, 4638, 8024, 6821, 3416, 4638, 6392, 6369,
         7599, 3419, 4692,  677, 1343,  738, 3221, 3227, 2533, 2523, 2399, 6768,
         2523, 1920, 3175, 4638, 8024, 6756, 6716, 5296, 3340,  738, 3221, 2523,
         3837, 4517, 4638, 8024, 6392, 6369, 4638, 2523, 3300, 2231, 3613, 2697,
          511, 6756, 1079, 4638, 6981, 5390, 6820, 3221, 3683, 6772,  705, 2168,
         7770, 5277, 4638, 8024, 2215, 1071, 3221,  704, 2971, 1920, 2242, 6392,
         6369, 4638, 2523, 3300, 4906, 2825, 2697, 8024, 1216, 5543,  738, 3221,
         3683, 6772, 7970, 1059, 4638, 8024, 3146,  860, 4638, 2141, 4500, 2595,
         6820, 3221, 2523, 2487, 4638,  511, 7674, 1044, 6821, 1378, 6756, 4638,
          817, 3419,  948,  679, 3221, 2523, 6586, 8024, 5445,  684, 6756, 1079,
         4638, 6981, 5390,  738, 6963, 3221, 3766, 2533, 6432, 4638, 8024, 2595,
         5543, 1392,  702, 3175, 7481, 6963, 3221, 2523,  679, 7231, 4638, 8024,
         2218, 3221, 2697, 6230, 6579, 6756, 4638, 3198,  952, 6929,  702,  831,
         2669, 3683, 6772, 2208,  511, 2769, 6230, 2533, 6821, 1378, 6756, 4638,
         1079, 7652, 6392, 6369, 4638, 2523, 7770, 5277, 8024, 1079, 7652, 6848,
         4500, 4638, 3332, 3160,  738, 6963, 3221, 2523,  831, 6574, 4638, 8024,
         6756, 1079,  738, 3766, 3300,  784,  720, 2460, 1456,  511,  102]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1.]])

**Comment by ysgncss** [comment]
貌似没啥问题呢

**Comment by ysgncss** [comment]
用不同的BERT它的序列是一样的，这个有问题吗？

**Comment by ysgncss** [comment]
解决了。把data/generated_data目录下的文件删除了就好了 . 感谢大佬！

**Comment by ysgncss** [comment]
如果我想进行在线测试，输入句子输出所有的三元组，我应该怎么做？
