### ISSUE TITLE
有关GPU训练的一些问题

### ISSUE THREAD

**Issue by insbread** [DianboWork/SPN4RE#16]
您好！
请问您在使用其他GPU的时候是直接指定--visible_gpu这个参数的吗？我指定这个参数之后模型并没有在指定的GPU上运行，请问您有遇到这个问题吗？您是怎么解决的？谢谢。

**Comment by DianboWork** [comment]
我重试了代码，并不存在这个问题，不知道你是否已经解决这个问题

**Comment by insbread** [comment]
非常感谢回复。我试了一下，是pytorch的版本问题。我用的是1.7.0的版本，好像这个版本是有一点bug的，所以代码里面设置GPU设备号的方法失效了。

**Comment by DianboWork** [comment]
我最近在另一个程序里也遇到了这个问题，我尝试了如下代码解决了
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = str(args.visible_gpu)
torch.cuda.set_device(args.visible_gpu)

**Comment by insbread** [comment]
好的，非常感谢你的回复
