### ISSUE TITLE
能提供更多的说明吗？

### ISSUE THREAD

**Issue by liutianling** [DianboWork/SPN4RE#2]
谢谢您的分享。
README部分信息太少了，能否增加一下说明信息。
比如，模型的表现，与其他方法的对比，是否支持重叠实体的关系抽取等，谢谢！

**Comment by DianboWork** [comment]
模型在WebNLG和NYT上是SoTA（https://paperswithcode.com/paper/joint-entity-and-relation-extraction-with-set  )， 和其他方法的对比可以参考文章（https://arxiv.org/abs/2011.01675， https://arxiv.org/pdf/2103.16929.pdf ），支持重叠实体的关系抽取

**Comment by liutianling** [comment]
好的，非常感谢，文章已下载，学习中！谢谢

**Comment by DianboWork** [comment]
https://github.com/DianboWork/PublicPresentation 这里面的ppt应该对理解joint entity and relation extraction有些帮助

**Comment by liutianling** [comment]
好的，非常感谢！
