### ISSUE TITLE
代码

### ISSUE THREAD

**Issue by mornsong** [DianboWork/SPN4RE#3]
您好，想问一下models/set_decoder.py中第124行一直报错，缺少BertAttention的attention_mask，应该如何修正

**Comment by IANAIAN** [comment]
没错，我也遇到这个问题

**Comment by DianboWork** [comment]
我这一两天会检查这个代码,麻烦稍等!

**Comment by IANAIAN** [comment]
感谢作者的分享和付出！
我在阅读了您的代码之后，除了训练过程中好像出现的运算错误（我找了一下BertAttention的实现，它确实要接受两个参数，代码里只传了一个），还发现一些参数名和函数名的笔误。所以希望您有时间的话，可以修正后测试一下代码是否能够正常运行，万分感谢！

**Comment by DianboWork** [comment]
@mornsong @IANAIAN 我已更新代码，并重新进行了测试，在我的机器上是没问题的，之前出现问题因为是代码对pytorch_transformers包支持不够好，建议使用transformers这个包

**Comment by DianboWork** [comment]
@IANAIAN 有哪些函数名和参数名的笔误，欢迎指出!

**Comment by IANAIAN** [comment]
作者你好，再次麻烦您，请问您的transformers的版本是什么呢？我用transformers的时候，代码中这一行：from transformers.modeling_bert import BertAttention后面一系列类会报错，提示transformers好像已经没有modeling_bert这个文件了呢？pytorch_transformers是有的，所以才用了后者。

**Comment by IANAIAN** [comment]
@DianboWork 看了一下您的最新代码，上个版本中的参数名和函数名不一致的问题已经解决🥳

**Comment by DianboWork** [comment]
@IANAIAN 我看到您的邮件,但没有看到对应issues,只能在这里回复您了.SPN4RE这个项目里的list_index函数非常粗糙,只适合NYT和WEBNLG, 您可以自己写自己的数据接口.如果数据集明确标注了实体位置的,我这有相应的函数,您可以提供邮箱,我传给您.

**Comment by IANAIAN** [comment]
非常感谢您的耐心解答，我可以这边尝试自己去写适合数据集的list_index，数据集其实结构和WebNLG很像，就是文本和关系三元组（两个实体和对应的关系），并无多余的实体位置信息了。

Sent from my iPhone

On Apr 6, 2021, at 6:39 PM, DianboWork ***@***.***> wrote:

﻿

@IANAIAN<https://github.com/IANAIAN> 我看到您的邮件,但没有看到对应issues,只能在这里回复您了.SPN4RE这个项目里的list_index函数非常粗糙,只适合NYT和WEBNLG, 您可以自己写自己的数据接口.如果数据集明确标注了实体位置的,我这有相应的函数,您可以提供邮箱,我传给您.
