### ISSUE TITLE
head_start_index, head_end_index = list_index(head_token, token_sent)

### ISSUE THREAD

**Issue by HelloJoyce** [DianboWork/SPN4RE#4]
这里load_data文件中，查找实体index，但是如果实体是bert词典没有的词，对应的它就是UNK，list_index方法使得它的index成为句子中最后一个UNK的index,这样的index不是错的吗？

**Comment by DianboWork** [comment]
头实体，尾实体和句子本身都是经过tokenizer的，如果实体是bert词典没有的词，BPE算法也会对该单词进行再拆分，也是可以查找到它的index的，一般不会出现UNK的情况，您也可以利用自己的方式去查找实体的位置https://github.com/DianboWork/SPN4RE/blob/0c3d01bb336f7fc9202aea8ccef08a369df163bc/utils/functions.py#L56-L57

**Comment by IANAIAN** [comment]
@DianboWork 作者你好，在利用list_index方法处理中文训练数据的时候，会出现实体开头index小于实体结尾index的情况，也就是那句assert会提示报错，然后还有就是list_index中会出现list下标越界（好像是这个问题）（IndexError）。不好意思具体的报错截图我当时没截，我就把这些异常全忽略 然后直接continue了，您能不能大致推测一下可能是什么原因呢 ？
