### ISSUE TITLE
模型推断

### ISSUE THREAD

**Issue by Coldders** [DianboWork/SPN4RE#5]
请问如何生成模型推断结果文件？以及何如加载已经训练好的模型做推断？
Readme貌似都没有提及，请问能解答一下吗，谢谢！

**Comment by DianboWork** [comment]
可以通过简单的修改Trainer中的eval_model函数实现这个功能

**Comment by Coldders** [comment]
> 可以通过简单的修改Trainer中的eval_model函数实现这个功能

感谢回复，已解决
