### ISSUE TITLE
batch_size和epoch设定问题

### ISSUE THREAD

**Issue by IANAIAN** [DianboWork/SPN4RE#6]
请问，训练集数据大约有17万多条，epoch要设置成多少才可以充分发挥模型多性能，batch_size又是多少合适呢？

**Comment by IANAIAN** [comment]
目前跑了epoch是50，batch_size是12的，最后也不知道loss降到最低水平了吗，因为最后发现都要好几个epoch的loss才能降低0.1这样子。

**Comment by DianboWork** [comment]
max_grad_norm；num_generated_triples和na_rel_coef 这三个参数对结果影响比较大，lr在有些任务上也比较重要，调lr的准则是encoder_lr设小，decoder_lr设大

**Comment by Power886** [comment]
你是跑的百度数据吗？在计算relation loss那块是不是有点问题

**Comment by Du-XiaoJing** [comment]
你是跑的百度数据吗？在计算relation loss那块是不是有点问题

**Comment by IANAIAN** [comment]
> 你是跑的百度数据吗？在计算relation loss那块是不是有点问题

是百度的那个比赛数据。我这边没问题，你只要把原始数据处理成模型支持的形式就行了，百度那个复杂关系有点特殊，不知道你是不是这个地方没有注意到。

**Comment by Power886** [comment]
我已经将复杂三元组转换为了简单三元组了，而且也对那个list_index进行修改了，你能不能留个qq或者微信交流下，我也在做百度那个比赛，目前均分66



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月14日(周三) 晚上9:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DianboWork/SPN4RE] batch_size和epoch设定问题 (#6)




  
你是跑的百度数据吗？在计算relation loss那块是不是有点问题
  
是百度的那个比赛数据。我这边没问题，你只要把原始数据处理成模型支持的形式就行了，百度那个复杂关系有点特殊，不知道你是不是这个地方没有注意到。

**Comment by IANAIAN** [comment]
qq：812583287

你是用这个spn的方法得到均分66的吗？那你不是已经跑通了吗？为什么还报错呢？
我第一次跑了一下，也是66.8左右，直接用num=10可能效果不好，有点少。加我qq交流一下吧！
Sent from my iPhone

On Apr 14, 2021, at 9:28 PM, Du-XiaoJing ***@***.***> wrote:

﻿

我已经将复杂三元组转换为了简单三元组了，而且也对那个list_index进行修改了，你能不能留个qq或者微信交流下，我也在做百度那个比赛，目前均分66



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月14日(周三) 晚上9:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DianboWork/SPN4RE] batch_size和epoch设定问题 (#6)





你是跑的百度数据吗？在计算relation loss那块是不是有点问题

是百度的那个比赛数据。我这边没问题，你只要把原始数据处理成模型支持的形式就行了，百度那个复杂关系有点特殊，不知道你是不是这个地方没有注意到。

**Comment by Power886** [comment]
不是，我是说三个子任务的均分在66以上，关系抽取这块用的另一个模型跑了728



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月14日(周三) 晚上10:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DianboWork/SPN4RE] batch_size和epoch设定问题 (#6)




 qq：812583287 
 
 你是用这个spn的方法得到均分66的吗？那你不是已经跑通了吗？为什么还报错呢？ 
 我第一次跑了一下，也是66.8左右，直接用num=10可能效果不好，有点少。加我qq交流一下吧！ 
 Sent from my iPhone 
 
 On Apr 14, 2021, at 9:28 PM, Du-XiaoJing ***@***.***&gt; wrote: 
 
 ﻿ 
 
 我已经将复杂三元组转换为了简单三元组了，而且也对那个list_index进行修改了，你能不能留个qq或者微信交流下，我也在做百度那个比赛，目前均分66 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2021年4月14日(周三) 晚上9:23 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [DianboWork/SPN4RE] batch_size和epoch设定问题 (#6) 
 
 
 
 
 
 你是跑的百度数据吗？在计算relation loss那块是不是有点问题 
 
 是百度的那个比赛数据。我这边没问题，你只要把原始数据处理成模型支持的形式就行了，百度那个复杂关系有点特殊，不知道你是不是这个地方没有注意到。
