### ISSUE TITLE
训练模型

### ISSUE THREAD

**Issue by Power886** [DianboWork/SPN4RE#7]
![E{4NW0X29_%)JP~9G4JMD~G](https://user-images.githubusercontent.com/67457827/114710778-b2f8c080-9d60-11eb-8ad6-0fef2cef0894.png)
这个错误如何解决？

**Comment by Power886** [comment]
这是跑的百度duie数据集，num_rel:55,百度搜索了一下说是索引问题，该如何解决

**Comment by DianboWork** [comment]
某个index超过了范围
