### ISSUE TITLE
关于论文Table 4的实验结果问题

### ISSUE THREAD

**Issue by Zeyu-Liang** [DianboWork/SPN4RE#8]
您好，感谢分享。有一个问题，论文table 4的实验结果：
<img width="461" alt="WX20210415-155216@2x" src="https://user-images.githubusercontent.com/20256760/114833865-99a85080-9e02-11eb-917c-0a618dd6b485.png">
我根据您提供源代码和命令行，效果只到0.928841, 请问，可以分享更详细的参数，或者训练过程用了哪些技巧么 ？感谢您的回复！
python -m main --bert_directory BERT_DIR --batch_size 4 --num_generated_triplets 10 --na_rel_coef 0.25 --max_grad_norm 20  --max_epoch 100 --encoder_lr 0.00002 --decoder_lr 0.00005 --num_decoder_layers 4 --max_span_length 10 --weight_decay 0.000001 --lr_decay 0.02

=== Epoch 73 Test ===
precision = 0.930599, recall = 0.927090, f1_value = 0.928841
rel_precision = 0.955205, rel_recall = 0.951603, rel_f1_value = 0.953401
ent_precision = 0.950158, ent_recall = 0.946574, ent_f1_value = 0.948363
Achieving Best Result on Test Set

**Comment by Zeyu-Liang** [comment]
Table 3

**Comment by DianboWork** [comment]
结果会受到随机数的影响（不同机器，即使使用相同的随机数种子，结果也会不同）
