### ISSUE TITLE
您好！想请教一下二部匹配损失和交叉熵损失的问题。

### ISSUE THREAD

**Issue by twosmallhands** [DianboWork/SPN4RE#9]
首先感谢您的论文和代码，然后想问一下，二部匹配之后使用的不还是交叉熵损失嘛，这一点没看懂，还有后边的对比实验里用的交叉熵又是啥？
![损失函数](https://user-images.githubusercontent.com/38624513/115257214-6fd48e00-a162-11eb-94e5-7329398d8f83.jpg)

![实验](https://user-images.githubusercontent.com/38624513/115257294-8844a880-a162-11eb-813e-3aaf544e23b2.jpg)

**Comment by Zeyu-Liang** [comment]
同样的疑惑， 同问，感谢！

**Comment by DianboWork** [comment]
和cross entropy的区别在于：1、二部匹配损失引入了匈牙利算法来计算predictions和ground-trurhs之间的对应关系，而cross entropy是假定predictions和ground-truths在输出时就已经匹配了。2、二部损失需要在关系类别中引入NA类，cross-entropy不需要。所以在计算完匹配关系之后，需要特别处理NA类，也就是截图里的公式

**Comment by twosmallhands** [comment]
谢谢您的回复~
